//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNameTestify.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandlordRegistration
    {
        public LandlordRegistration()
        {
            this.LandlordHouseDetails = new HashSet<LandlordHouseDetail>();
        }
    
        public int LandlordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PPSNNO { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string TokenId { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual ICollection<LandlordHouseDetail> LandlordHouseDetails { get; set; }
    }
}
