//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNameTestify.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandlordHouseDetail
    {
        public LandlordHouseDetail()
        {
            this.TenantRegistrations = new HashSet<TenantRegistration>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LandlordId { get; set; }
        public string PRTBNO { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual LandlordRegistration LandlordRegistration { get; set; }
        public virtual ICollection<TenantRegistration> TenantRegistrations { get; set; }
    }
}
